# ~/.config/fuzzel/fuzzel.ini

font=IBM Plex Mono:size=11
dpi-aware=auto
icon-theme=Everforest-Dark
show-actions=no
terminal=alacritty

lines=12
width=40
tabs=4
horizontal-pad=24
vertical-pad=18
inner-pad=12

image-size-ratio=0.5
line-height=26

[colors]
background=2b3339ff       
text=d3c6aaff             
match=dbbc7fff            
selection=3a454aff        
selection-text=e6e2ccff   
selection-match=dbbc7fff  
border=a7c080ff           

[border]
width=2
radius=6

[dmenu]
mode=text
exit-immediately-if-empty=no
